language: ruby
sudo: required
dist: trusty
rvm:
  - 2.5.0
env:
  - DB=postgresql
bundler_args: "--without production"
cache: bundler
addons:
  chrome: stable
before_script:
  - export TZ=Asia/Tokyo
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database database_test' -U postgres
  - bundle update
script:
  - RAILS_ENV=test bin/rails db:migrate
  - bin/rails test
  - bin/rails test:system
